/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.leetcode.arrays

import spock.lang.Specification

class RemoveDuplicateSpec extends Specification {
    RemoveDuplicatesClass removeDuplicatesClass= new RemoveDuplicatesClass();
    def "should return array with no duplicate"() {
        given:
        //def birdArr = ["Parrot", "Cockatiel", "Pigeon"] as String[]
        def arr=[1,1,2,3,4,4] as int[]
        when :
        def result= removeDuplicatesClass.removeDuplicates(arr)
        then:
        result
        print result
    }
}
