/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leetcode.arrays;

public class App {
    //public String getGreeting() {
       // return "Hello World!";
   // }

    public static void main(String[] args) {
//        int[]arr={1,1,2,3,4,5};
//        System.out.println(new RemoveDuplicatesClass().removeDuplicates(arr));
        ThreeSum threeSum= new ThreeSum();

        threeSum.threeSum(new int []{-1,0,1,2,-1,-4} );
    }
}
